### ISSUE TITLE
Animated assets

### ISSUE THREAD

**Issue by SoftCreatR** [daniel-tran/steam-points-shop-search#3]
It would be nice if animated assets, such as backgrounds, and avatars, were supported as well.

EDIT:

Nevermind, looks like the API doesn't return them.

**Comment by daniel-tran** [comment]
I remember the API does provide links to the animated images of assets if there is one, but it's not an intuitive system - You basically have to look for `"animated":true` in the specific asset data given by the API and then load the image listed in the `item_image_small` property. There are other nuances around this, which are hopefully all captured in dd2dd97fdac33daf77e14b956350aee321b1f8b5.

The latest site should have that change applied now, so I'll leave this issue open for a few more days in the event someone notices anything that's missing or incorrect.
